language: go

go:
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - master

before_install:
  - go get -v golang.org/x/lint/golint
  - go get -u github.com/golangci/golangci-lint/cmd/golangci-lint

script:
  - go test -v -race ./...
  - golangci-lint run
