
[[constraint]]
  name = "github.com/golang/protobuf"
  branch = "master"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.1"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.17.0"

[prune]
  go-tests = true
  unused-packages = true
