
[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/golang/protobuf"
  branch = "master"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.1"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.17.0"


[[constraint]]
  name = "github.com/caarlos0/env"
  version = "3.5.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/gordonklaus/portaudio"

[[constraint]]
  name = "cloud.google.com/go"
  version = "0.34.0"

[[constraint]]
  branch = "master"
  name = "github.com/go-audio/audio"

[[constraint]]
  branch = "master"
  name = "github.com/go-audio/wav"
